config/routes.rb
Demo::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
 
  resources :orders do 
 get 'destroy', to: 'orders#destroy',as: :destroy
  end

  resources :line_items
  resources :carts
  get "store/index"

 resources :products do
  get :who_bought, :on => :member
  get 'destroy', to: 'products#destroy',as: :destroy
 end

resources :users do
  match '/signup',  to: 'users#new', via: 'get'
  get 'destroy', to: 'users#destroy', as: :destroy
 end

   root :to => 'store#index' 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pragprog Books Online Store</title>
<%= stylesheet_link_tag "scaffolds" %>
<%= javascript_include_tag 'application' %>
<%= stylesheet_link_tag "depot" , :media => "all" %>
<%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
<%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
<%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>  
<%= csrf_meta_tag %>
</head>
<body id="store">
<div id="banner">
<%#= image_tag("logo.png" ) %>
<%= @page_title || "Matic Bookshelf" %>
</div>
<div id="columns" >
<div id="side" >
<!-- <div id="cart" >
 --><%#= render @cart %>
<% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, :id => "cart" ) do %>
          <%= render @cart %>
        <% end %>
      <% end %>
 <% if session[:user_id] %>
 <table border ="1">
      <%= link_to 'Home' , store_index_path %><br />
     <%= link_to 'Orders' ,orders_path %><br>
     <%= link_to 'Products' , products_path %><br />
     <%= link_to 'Users' ,users_path %><br /><br>  
    <%= button_to 'Logout' , logout_path, :method => :delete %><br />
 <% else %>
    <br />
    <td align ="center"> <%= button_to 'Signin' , login_path %><br /></td>
 <% end %>
  </table>
  </div>
  <div id="main">
    <%= yield %>
  </div>
 </div>
</body>
</html>